### ISSUE TITLE
UAVSAR tutorial plots not rendering

### ISSUE THREAD

**Issue by hpmarshall** [snowex-hackweek/website#115]
For some reason, although only a few sentences of text only was changed on the last pull request, most of the plots on the UAVSAR tutorial are no longer rendering.

**Comment by jomey** [comment]
There is a AWS timeout issue for the requested AWS auth token when pulling the tutorial data from S3. Deploys with GitHub actions can take up to 40 mins. [Example here](https://github.com/snowex-hackweek/website/runs/3050855222?check_suite_focus=true#step:6:123)
