### ISSUE TITLE
Link repository to zenodo DOI

### ISSUE THREAD

**Issue by scottyhq** [snowex-hackweek/website#15]
tutorial documenting how to do this is here:
https://guides.github.com/activities/citable-code/ 

we want to make sure a release is made at the end of the hackweek so that all content contributors are listed

**Comment by scottyhq** [comment]
I wasn't seeing any of the snowex-hackweek repos logged into zenodo and came across this solution https://github.com/zenodo/zenodo/issues/1814#issuecomment-620555444

**Comment by scottyhq** [comment]
Plan for releasing a reproducible version of the website. cc @aaarendt @jomey 

1. Need to move any datasets used to make plots into a single repository because `s3://snowex-data/tutorial-data` will not last forever and as we saw during tutorials, sometimes servers are down so pulling data when running notebooks can be unreliable. Finally, if people want to run these examples a year from now, what happens if servers no longer exist or data versioning and urls are different! 

There are two strategies here and I think the best one is to create a zenodo record for tutorial data and a second record for the website. If there data is very small it can be stored in a github repo, but we have some large rasters. Here is a quick comparison between those options:

| data store 	|		total size	 limit |	single file limit |
| - | - | - |	
Zenodo Record 	|	50 GB	|	2 GB |
Github Repository	 |	1 GB - 5 GB* | 	100 MB** |

`* “strongly recommended”  ** strict` 

If we create a zenodo record the tutorials could start with this cell:
`wget https://zenodo.org/record/RECORD_ID/files/snowex-hackweek/tutorial-data.zip`

2. Many tutorials use the database. The location of the database may change, so what would it take to reserve a more permanant domain name that can map to any IP? For example `snowex-data.io?` cc @micahjohnson150 @hpmarshall 


3. Need to lock in the environment in this repository from 'latest' to the date stamp used '2021.07.07'
https://github.com/snowex-hackweek/website/blob/391e0cd8bed13f6325777070e6fe0cad3aff01e3/.github/workflows/deploy.yaml#L12

Anything else i'm missing?

**Comment by jomey** [comment]
Another solution for the data could be to use a git submodule:
https://www.atlassian.com/git/tutorials/git-submodule

The module could be the https://github.com/snowex-hackweek/tutorial-data

I feel that the file size limit of 100MB for a GitHub repository sounds reasonable, given that we should aim for the notebooks to execute rather quick. Long running notebooks might deter people from looking at them as well.

**Comment by hpmarshall** [comment]
This is awesome @scottyhq thanks for putting this together.  I'll figure out the domain name.  The last few letters don't matter correct?  Nothing special about .io?  Its more expensive...

**Comment by hpmarshall** [comment]
And I agree that a zenodo for the tutorial data sounds like what we need for the larger datasets.  We can reduce the number of UAVSAR rasters on s3 before we do that...the tutorial only used a few and the project downloaded many more.

**Comment by scottyhq** [comment]
> This is awesome @scottyhq thanks for putting this together. I'll figure out the domain name. The last few letters don't matter correct? Nothing special about .io? Its more expensive... 

I've had colleagues use .pizza b/c it is hillarious and cheap :) It can be whatever you want, For data oriented things .io is common. I've also seen .xyz or even .org.  We pay $39 / year for  hackweek.io , which we obtained via https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/registrar.html

**Comment by jomey** [comment]
You can pick any domain name.

My current provider is hover.com and I have only good things to day (Can't pick on Canada anyways).

I suggest: [snowexdata.org](https://www.hover.com/domains/results?q=snowex-data.org)
Cheapest option and very common suffix

**Comment by jomey** [comment]
Interesting arguments for a .org domain
https://thenew.org/org-people/domain-products/org/

**Comment by hpmarshall** [comment]
Done!  We now have "snowexdata.org".  I like the org arguments.

**Comment by scottyhq** [comment]
Awesome! @micahjohnson150 could you please map the database IP to a URL under snowexdata.org and confirm the database tutorial notebook works with that new URL? We've used this https://dns.he.net/ service for mappings in the past, I'm sure there are alternatives or maybe whatever service was used to obtain snowexdata.org can do this mapping. 

I'm envisioning `https://database.snowexdata.org` but again, this is up to you
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#using-a-subdomain-for-your-github-pages-site

**Comment by micahjohnson150** [comment]
Definitely. It will take me a couple days to make sure its full flushed out. Thanks for the resource suggestion!

**Comment by jomey** [comment]
I can vouch for the hover DNS (if purchased through there). Has also not failed me in the past.

As for url - I like the suggestion. You can also shorten it up and do `db.snowexdata.org`, but that's my fat fingers speaking that like to misspell things.

**Comment by hpmarshall** [comment]
just let me know where to point snowexdata.org to.  I guess it would be the jupyterhub for the next month while we figure out how to host long-term?
