### ISSUE TITLE
NASA earthdata authentication for building website

### ISSUE THREAD

**Issue by scottyhq** [snowex-hackweek/website#70]
We want to be able for GitHub Actions to run tutorial notebooks top-to-bottom to ensure that they run. Unfortunately, API-based access to NASA data (via `curl` and `wget`) is setup for [using a ~/.netrc file](https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+cURL+And+Wget) rather than reading from environment variables or being able to specify a temporary token. This means we'll have to use a "machine user" with a NASA URS https://urs.earthdata.nasa.gov login and somehow inject those credentials into the continuous integration system.

**Comment by JessicaS11** [comment]
It's not yet merged into a release or the development branch, but @tsutterly did some awesome work ([PR#200](https://github.com/icesat2py/icepyx/pull/200)) on enabling Earthdata access using environment variables within icepyx. It's all in the [standalone, with wrappers from an ICESat-2 Query object] [Earthdata module](https://github.com/icesat2py/icepyx/blob/credentials/icepyx/core/Earthdata.py), currently still on the credentials branch. icepyx is also set up to run some CI testing on Travis that's behind the Earthdata login. We're still finalizing a bunch of these things, but you might be able to borrow the Earthdata module until you can just install it via icepyx to make use of the environment variable login currently (there's also an [open PR](https://github.com/icesat2py/icepyx/pull/213) that gets an s3 token for ICESat-2 data using the Earthdata credentials, if you're on the beta-tester list). Happy to chat more about this!
