### ISSUE TITLE
update preliminary work section

### ISSUE THREAD

**Issue by scottyhq** [snowex-hackweek/website#9]
the preliminary work section of the website currently has a lot of material specific to icesat2 hackweek. just making an issue to keep track and will follow up with a PR to make things either generic or specific to snowex hackweek. https://snowex-hackweek.github.io/website/preliminary/index.html

**Comment by aaarendt** [comment]
Yes, we need to get going on this soon. I just brought over everything from ICESat-2 for now. It would be great to make this generic as much as possible for use with other events.

**Comment by scottyhq** [comment]
closed by and #26  #30
